export const initialEmployees = [
  {
    "id": "emp-001",
    "firstName": "Amit",
    "lastName": "Lakade",
    "email": "amit.lakade@company.com",
    "phone": "+91-9876500000",
    "department": "Executive",
    "designation": "Chief Executive Officer",
    "status": "active",
    "joiningDate": "2015-01-10",
    "dateOfBirth": "1980-05-14",
    "performanceRating": "Outstanding",
    "salary": 5000000,
    "avatar": null,
    "documents": [],
    "address": "Koregaon Park, Pune",
    "managerId": null
  },
  {
    "id": "emp-002",
    "firstName": "Anagha",
    "lastName": "Babar",
    "email": "anagha.babar@company.com",
    "phone": "+91-9876537069",
    "department": "Engineering",
    "designation": "Engineering Manager",
    "status": "active",
    "joiningDate": "2020-06-19",
    "dateOfBirth": "1989-07-08",
    "performanceRating": "Outstanding",
    "salary": 3371360,
    "avatar": null,
    "documents": [],
    "address": "Baner, Pune",
    "managerId": "emp-001"
  },
  {
    "id": "emp-003",
    "firstName": "Rajashree",
    "lastName": "Sawant",
    "email": "rajashree.sawant@company.com",
    "phone": "+91-9876535660",
    "department": "Sales",
    "designation": "Sales Director",
    "status": "active",
    "joiningDate": "2021-03-20",
    "dateOfBirth": "1985-03-15",
    "performanceRating": "Needs Improvement",
    "salary": 3448658,
    "avatar": null,
    "documents": [],
    "address": "Sinhagad Road, Pune",
    "managerId": "emp-001"
  },
  {
    "id": "emp-004",
    "firstName": "Swaranjali",
    "lastName": "Tupe",
    "email": "swaranjali.tupe@company.com",
    "phone": "+91-9876537609",
    "department": "Human Resources",
    "designation": "HR Director",
    "status": "active",
    "joiningDate": "2022-05-30",
    "dateOfBirth": "1988-12-09",
    "performanceRating": "Meets Expectations",
    "salary": 3194458,
    "avatar": null,
    "documents": [],
    "address": "Balewadi, Pune",
    "managerId": "emp-001"
  },
  {
    "id": "emp-005",
    "firstName": "Nidhi",
    "lastName": "Gaikwad",
    "email": "nidhi.gaikwad@company.com",
    "phone": "+91-9876526578",
    "department": "Finance",
    "designation": "Finance Director",
    "status": "active",
    "joiningDate": "2019-05-02",
    "dateOfBirth": "1988-11-01",
    "performanceRating": "Needs Improvement",
    "salary": 2846205,
    "avatar": null,
    "documents": [],
    "address": "Pashan, Pune",
    "managerId": "emp-001"
  },
  {
    "id": "emp-006",
    "firstName": "Subhash",
    "lastName": "Bhalerao",
    "email": "subhash.bhalerao@company.com",
    "phone": "+91-9876532478",
    "department": "Marketing",
    "designation": "Marketing Director",
    "status": "active",
    "joiningDate": "2021-11-02",
    "dateOfBirth": "1982-10-26",
    "performanceRating": "Needs Improvement",
    "salary": 3256056,
    "avatar": null,
    "documents": [],
    "address": "Hadapsar, Pune",
    "managerId": "emp-001"
  },
  {
    "id": "emp-007",
    "firstName": "Akshata",
    "lastName": "Dhasal",
    "email": "akshata.dhasal@company.com",
    "phone": "+91-9876553656",
    "department": "Operations",
    "designation": "Operations Director",
    "status": "active",
    "joiningDate": "2018-09-30",
    "dateOfBirth": "1983-08-17",
    "performanceRating": "Exceeds Expectations",
    "salary": 3422466,
    "avatar": null,
    "documents": [],
    "address": "Viman Nagar, Pune",
    "managerId": "emp-001"
  },
  {
    "id": "emp-008",
    "firstName": "Avinash",
    "lastName": "Chavan",
    "email": "avinash.chavan@company.com",
    "phone": "+91-9876565808",
    "department": "Product",
    "designation": "Product Director",
    "status": "active",
    "joiningDate": "2021-09-28",
    "dateOfBirth": "1984-12-23",
    "performanceRating": "Exceeds Expectations",
    "salary": 2947925,
    "avatar": null,
    "documents": [],
    "address": "Camp, Pune",
    "managerId": "emp-001"
  },
  {
    "id": "emp-009",
    "firstName": "Ranjit",
    "lastName": "Zambare",
    "email": "ranjit.zambare@company.com",
    "phone": "+91-9876521324",
    "department": "Design",
    "designation": "Design Director",
    "status": "active",
    "joiningDate": "2021-07-07",
    "dateOfBirth": "1987-06-23",
    "performanceRating": "Meets Expectations",
    "salary": 3048604,
    "avatar": null,
    "documents": [],
    "address": "Kothrud, Pune",
    "managerId": "emp-001"
  },
  {
    "id": "emp-010",
    "firstName": "Mahesh",
    "lastName": "Kale",
    "email": "mahesh.kale@company.com",
    "phone": "+91-9876535914",
    "department": "Engineering",
    "designation": "Tech Lead",
    "status": "active",
    "joiningDate": "2023-03-12",
    "dateOfBirth": "1995-05-28",
    "performanceRating": "Meets Expectations",
    "salary": 1796187,
    "avatar": null,
    "documents": [],
    "address": "Deccan Gymkhana, Pune",
    "managerId": "emp-002"
  },
  {
    "id": "emp-011",
    "firstName": "Sonali",
    "lastName": "Zende",
    "email": "sonali.zende@company.com",
    "phone": "+91-9876549528",
    "department": "Engineering",
    "designation": "Tech Lead",
    "status": "active",
    "joiningDate": "2024-02-05",
    "dateOfBirth": "1990-08-01",
    "performanceRating": "Needs Improvement",
    "salary": 1698502,
    "avatar": null,
    "documents": [],
    "address": "Balewadi, Pune",
    "managerId": "emp-002"
  },
  {
    "id": "emp-012",
    "firstName": "Manisha",
    "lastName": "Bhandari",
    "email": "manisha.bhandari@company.com",
    "phone": "+91-9876529112",
    "department": "Sales",
    "designation": "Sales Manager",
    "status": "active",
    "joiningDate": "2021-08-02",
    "dateOfBirth": "1989-12-28",
    "performanceRating": "Exceeds Expectations",
    "salary": 1881551,
    "avatar": null,
    "documents": [],
    "address": "Wagholi, Pune",
    "managerId": "emp-003"
  },
  {
    "id": "emp-013",
    "firstName": "Urmila",
    "lastName": "Ghuge",
    "email": "urmila.ghuge@company.com",
    "phone": "+91-9876592961",
    "department": "Human Resources",
    "designation": "HR Manager",
    "status": "active",
    "joiningDate": "2024-04-17",
    "dateOfBirth": "1990-08-03",
    "performanceRating": "Meets Expectations",
    "salary": 1876587,
    "avatar": null,
    "documents": [],
    "address": "Aundh, Pune",
    "managerId": "emp-004"
  },
  {
    "id": "emp-014",
    "firstName": "Apurva",
    "lastName": "Ghorpade",
    "email": "apurva.ghorpade@company.com",
    "phone": "+91-9876541439",
    "department": "Finance",
    "designation": "Financial Analyst",
    "status": "active",
    "joiningDate": "2021-08-04",
    "dateOfBirth": "1987-01-08",
    "performanceRating": "Meets Expectations",
    "salary": 1524750,
    "avatar": null,
    "documents": [],
    "address": "Magarpatta, Pune",
    "managerId": "emp-005"
  },
  {
    "id": "emp-015",
    "firstName": "Vijay",
    "lastName": "Koli",
    "email": "vijay.koli@company.com",
    "phone": "+91-9876522157",
    "department": "Finance",
    "designation": "Financial Analyst",
    "status": "active",
    "joiningDate": "2022-09-16",
    "dateOfBirth": "1990-08-05",
    "performanceRating": "Needs Improvement",
    "salary": 1939778,
    "avatar": null,
    "documents": [],
    "address": "Kothrud, Pune",
    "managerId": "emp-005"
  },
  {
    "id": "emp-016",
    "firstName": "Priyanka",
    "lastName": "Mahadik",
    "email": "priyanka.mahadik@company.com",
    "phone": "+91-9876593605",
    "department": "Marketing",
    "designation": "Marketing Manager",
    "status": "on-leave",
    "joiningDate": "2023-10-09",
    "dateOfBirth": "1989-03-31",
    "performanceRating": "Exceeds Expectations",
    "salary": 1969395,
    "avatar": null,
    "documents": [],
    "address": "Kalyani Nagar, Pune",
    "managerId": "emp-006"
  },
  {
    "id": "emp-017",
    "firstName": "Siddharth",
    "lastName": "Mane",
    "email": "siddharth.mane@company.com",
    "phone": "+91-9876594475",
    "department": "Marketing",
    "designation": "Marketing Manager",
    "status": "inactive",
    "joiningDate": "2022-03-20",
    "dateOfBirth": "1992-03-21",
    "performanceRating": "Meets Expectations",
    "salary": 1725476,
    "avatar": null,
    "documents": [],
    "address": "Hinjewadi, Pune",
    "managerId": "emp-006"
  },
  {
    "id": "emp-018",
    "firstName": "Mayur",
    "lastName": "Deshmukh",
    "email": "mayur.deshmukh@company.com",
    "phone": "+91-9876563532",
    "department": "Operations",
    "designation": "Operations Lead",
    "status": "active",
    "joiningDate": "2024-01-29",
    "dateOfBirth": "1994-02-04",
    "performanceRating": "Needs Improvement",
    "salary": 1781896,
    "avatar": null,
    "documents": [],
    "address": "Bavdhan, Pune",
    "managerId": "emp-007"
  },
  {
    "id": "emp-019",
    "firstName": "Hemant",
    "lastName": "Shinde",
    "email": "hemant.shinde@company.com",
    "phone": "+91-9876520559",
    "department": "Product",
    "designation": "Product Manager",
    "status": "active",
    "joiningDate": "2023-12-06",
    "dateOfBirth": "1989-08-26",
    "performanceRating": "Meets Expectations",
    "salary": 1992554,
    "avatar": null,
    "documents": [],
    "address": "Deccan Gymkhana, Pune",
    "managerId": "emp-008"
  },
  {
    "id": "emp-020",
    "firstName": "Siddharth",
    "lastName": "Deshmukh",
    "email": "siddharth.deshmukh@company.com",
    "phone": "+91-9876585780",
    "department": "Product",
    "designation": "Product Manager",
    "status": "active",
    "joiningDate": "2024-01-08",
    "dateOfBirth": "1995-12-14",
    "performanceRating": "Meets Expectations",
    "salary": 1687870,
    "avatar": null,
    "documents": [],
    "address": "Baner, Pune",
    "managerId": "emp-008"
  },
  {
    "id": "emp-021",
    "firstName": "Nikhil",
    "lastName": "Khandagale",
    "email": "nikhil.khandagale@company.com",
    "phone": "+91-9876545635",
    "department": "Design",
    "designation": "UI/UX Designer",
    "status": "active",
    "joiningDate": "2024-05-03",
    "dateOfBirth": "1991-09-21",
    "performanceRating": "Exceeds Expectations",
    "salary": 1671827,
    "avatar": null,
    "documents": [],
    "address": "Wagholi, Pune",
    "managerId": "emp-009"
  },
  {
    "id": "emp-022",
    "firstName": "Nidhi",
    "lastName": "Pawar",
    "email": "nidhi.pawar@company.com",
    "phone": "+91-9876587358",
    "department": "Design",
    "designation": "UI/UX Designer",
    "status": "on-leave",
    "joiningDate": "2022-07-21",
    "dateOfBirth": "1989-09-17",
    "performanceRating": "Meets Expectations",
    "salary": 1771868,
    "avatar": null,
    "documents": [],
    "address": "Sinhagad Road, Pune",
    "managerId": "emp-009"
  },
  {
    "id": "emp-023",
    "firstName": "Akshata",
    "lastName": "Jadhav",
    "email": "akshata.jadhav@company.com",
    "phone": "+91-9876590095",
    "department": "Finance",
    "designation": "Accountant",
    "status": "active",
    "joiningDate": "2023-08-05",
    "dateOfBirth": "2004-02-25",
    "performanceRating": "Meets Expectations",
    "salary": 553672,
    "avatar": null,
    "documents": [],
    "address": "Deccan Gymkhana, Pune",
    "managerId": "emp-014"
  },
  {
    "id": "emp-024",
    "firstName": "Manasi",
    "lastName": "Kumbhar",
    "email": "manasi.kumbhar@company.com",
    "phone": "+91-9876556695",
    "department": "Product",
    "designation": "Product Owner",
    "status": "on-leave",
    "joiningDate": "2026-04-15",
    "dateOfBirth": "1996-05-11",
    "performanceRating": "Exceeds Expectations",
    "salary": 569583,
    "avatar": null,
    "documents": [],
    "address": "Pashan, Pune",
    "managerId": "emp-019"
  },
  {
    "id": "emp-025",
    "firstName": "Rajesh",
    "lastName": "Bhandari",
    "email": "rajesh.bhandari@company.com",
    "phone": "+91-9876561363",
    "department": "Design",
    "designation": "Graphic Designer",
    "status": "inactive",
    "joiningDate": "2026-03-31",
    "dateOfBirth": "2001-04-18",
    "performanceRating": "Exceeds Expectations",
    "salary": 1201438,
    "avatar": null,
    "documents": [],
    "address": "Wagholi, Pune",
    "managerId": "emp-021"
  },
  {
    "id": "emp-026",
    "firstName": "Pranjal",
    "lastName": "Teli",
    "email": "pranjal.teli@company.com",
    "phone": "+91-9876514435",
    "department": "Engineering",
    "designation": "Senior Developer",
    "status": "on-leave",
    "joiningDate": "2024-04-21",
    "dateOfBirth": "2002-07-05",
    "performanceRating": "Meets Expectations",
    "salary": 845846,
    "avatar": null,
    "documents": [],
    "address": "Camp, Pune",
    "managerId": "emp-011"
  },
  {
    "id": "emp-027",
    "firstName": "Pratiksha",
    "lastName": "Sable",
    "email": "pratiksha.sable@company.com",
    "phone": "+91-9876548952",
    "department": "Finance",
    "designation": "Accountant",
    "status": "active",
    "joiningDate": "2025-02-08",
    "dateOfBirth": "1996-05-25",
    "performanceRating": "Needs Improvement",
    "salary": 743328,
    "avatar": null,
    "documents": [],
    "address": "Pimple Saudagar, Pune",
    "managerId": "emp-014"
  },
  {
    "id": "emp-028",
    "firstName": "Pratik",
    "lastName": "Jadhav",
    "email": "pratik.jadhav@company.com",
    "phone": "+91-9876529523",
    "department": "Design",
    "designation": "Graphic Designer",
    "status": "active",
    "joiningDate": "2026-06-09",
    "dateOfBirth": "1996-10-16",
    "performanceRating": "Exceeds Expectations",
    "salary": 1113002,
    "avatar": null,
    "documents": [],
    "address": "Aundh, Pune",
    "managerId": "emp-022"
  },
  {
    "id": "emp-029",
    "firstName": "Urmila",
    "lastName": "Dhumal",
    "email": "urmila.dhumal@company.com",
    "phone": "+91-9876564358",
    "department": "Design",
    "designation": "Graphic Designer",
    "status": "notice-period",
    "joiningDate": "2025-04-22",
    "dateOfBirth": "1996-06-16",
    "performanceRating": "Exceeds Expectations",
    "salary": 648015,
    "avatar": null,
    "documents": [],
    "address": "Hinjewadi, Pune",
    "managerId": "emp-021"
  },
  {
    "id": "emp-030",
    "firstName": "Bhakti",
    "lastName": "Pingle",
    "email": "bhakti.pingle@company.com",
    "phone": "+91-9876555568",
    "department": "Finance",
    "designation": "Accountant",
    "status": "active",
    "joiningDate": "2023-10-24",
    "dateOfBirth": "1996-10-25",
    "performanceRating": "Meets Expectations",
    "salary": 891186,
    "avatar": null,
    "documents": [],
    "address": "Wagholi, Pune",
    "managerId": "emp-015"
  },
  {
    "id": "emp-031",
    "firstName": "Bhakti",
    "lastName": "Mhaske",
    "email": "bhakti.mhaske@company.com",
    "phone": "+91-9876542660",
    "department": "Finance",
    "designation": "Accountant",
    "status": "active",
    "joiningDate": "2024-11-24",
    "dateOfBirth": "2003-01-22",
    "performanceRating": "Outstanding",
    "salary": 951907,
    "avatar": null,
    "documents": [],
    "address": "Pimple Saudagar, Pune",
    "managerId": "emp-014"
  },
  {
    "id": "emp-032",
    "firstName": "Mayur",
    "lastName": "Avhad",
    "email": "mayur.avhad@company.com",
    "phone": "+91-9876599155",
    "department": "Product",
    "designation": "Product Owner",
    "status": "active",
    "joiningDate": "2025-05-23",
    "dateOfBirth": "2004-01-23",
    "performanceRating": "Meets Expectations",
    "salary": 980905,
    "avatar": null,
    "documents": [],
    "address": "Hinjewadi, Pune",
    "managerId": "emp-019"
  },
  {
    "id": "emp-033",
    "firstName": "Shrikant",
    "lastName": "Magar",
    "email": "shrikant.magar@company.com",
    "phone": "+91-9876574684",
    "department": "Finance",
    "designation": "Accountant",
    "status": "active",
    "joiningDate": "2025-10-08",
    "dateOfBirth": "1993-06-04",
    "performanceRating": "Exceeds Expectations",
    "salary": 1228977,
    "avatar": null,
    "documents": [],
    "address": "Baner, Pune",
    "managerId": "emp-015"
  },
  {
    "id": "emp-034",
    "firstName": "Reshma",
    "lastName": "Mahadik",
    "email": "reshma.mahadik@company.com",
    "phone": "+91-9876554877",
    "department": "Product",
    "designation": "Product Owner",
    "status": "active",
    "joiningDate": "2025-07-07",
    "dateOfBirth": "1997-05-25",
    "performanceRating": "Meets Expectations",
    "salary": 1276260,
    "avatar": null,
    "documents": [],
    "address": "Hinjewadi, Pune",
    "managerId": "emp-020"
  },
  {
    "id": "emp-035",
    "firstName": "Nisha",
    "lastName": "Bhosale",
    "email": "nisha.bhosale@company.com",
    "phone": "+91-9876550873",
    "department": "Engineering",
    "designation": "Senior Developer",
    "status": "active",
    "joiningDate": "2023-10-16",
    "dateOfBirth": "1993-04-09",
    "performanceRating": "Meets Expectations",
    "salary": 1071437,
    "avatar": null,
    "documents": [],
    "address": "Wagholi, Pune",
    "managerId": "emp-011"
  },
  {
    "id": "emp-036",
    "firstName": "Rakesh",
    "lastName": "Bhandari",
    "email": "rakesh.bhandari@company.com",
    "phone": "+91-9876514247",
    "department": "Finance",
    "designation": "Accountant",
    "status": "on-leave",
    "joiningDate": "2024-06-23",
    "dateOfBirth": "2004-06-02",
    "performanceRating": "Meets Expectations",
    "salary": 946675,
    "avatar": null,
    "documents": [],
    "address": "Kothrud, Pune",
    "managerId": "emp-015"
  },
  {
    "id": "emp-037",
    "firstName": "Apeksha",
    "lastName": "Kumbhar",
    "email": "apeksha.kumbhar@company.com",
    "phone": "+91-9876592793",
    "department": "Product",
    "designation": "Product Owner",
    "status": "active",
    "joiningDate": "2026-07-29",
    "dateOfBirth": "2004-05-13",
    "performanceRating": "Meets Expectations",
    "salary": 622213,
    "avatar": null,
    "documents": [],
    "address": "Hadapsar, Pune",
    "managerId": "emp-020"
  },
  {
    "id": "emp-038",
    "firstName": "Madhuri",
    "lastName": "Waghmare",
    "email": "madhuri.waghmare@company.com",
    "phone": "+91-9876582944",
    "department": "Operations",
    "designation": "Operations Analyst",
    "status": "active",
    "joiningDate": "2025-02-03",
    "dateOfBirth": "1996-08-30",
    "performanceRating": "Exceeds Expectations",
    "salary": 1188205,
    "avatar": null,
    "documents": [],
    "address": "Camp, Pune",
    "managerId": "emp-018"
  },
  {
    "id": "emp-039",
    "firstName": "Sanjana",
    "lastName": "Nikam",
    "email": "sanjana.nikam@company.com",
    "phone": "+91-9876511932",
    "department": "Marketing",
    "designation": "SEO Expert",
    "status": "active",
    "joiningDate": "2026-05-15",
    "dateOfBirth": "1996-08-20",
    "performanceRating": "Outstanding",
    "salary": 975631,
    "avatar": null,
    "documents": [],
    "address": "Koregaon Park, Pune",
    "managerId": "emp-016"
  },
  {
    "id": "emp-040",
    "firstName": "Rutuja",
    "lastName": "Raskar",
    "email": "rutuja.raskar@company.com",
    "phone": "+91-9876569886",
    "department": "Operations",
    "designation": "Operations Analyst",
    "status": "active",
    "joiningDate": "2023-12-09",
    "dateOfBirth": "1993-10-31",
    "performanceRating": "Exceeds Expectations",
    "salary": 1039370,
    "avatar": null,
    "documents": [],
    "address": "Bhosari, Pune",
    "managerId": "emp-018"
  },
  {
    "id": "emp-041",
    "firstName": "Sanika",
    "lastName": "Shelar",
    "email": "sanika.shelar@company.com",
    "phone": "+91-9876587918",
    "department": "Design",
    "designation": "Graphic Designer",
    "status": "active",
    "joiningDate": "2023-09-08",
    "dateOfBirth": "2001-05-03",
    "performanceRating": "Meets Expectations",
    "salary": 936758,
    "avatar": null,
    "documents": [],
    "address": "Hadapsar, Pune",
    "managerId": "emp-021"
  },
  {
    "id": "emp-042",
    "firstName": "Rohit",
    "lastName": "Raut",
    "email": "rohit.raut@company.com",
    "phone": "+91-9876550361",
    "department": "Design",
    "designation": "Graphic Designer",
    "status": "active",
    "joiningDate": "2026-07-14",
    "dateOfBirth": "2001-12-22",
    "performanceRating": "Meets Expectations",
    "salary": 756069,
    "avatar": null,
    "documents": [],
    "address": "Wagholi, Pune",
    "managerId": "emp-021"
  },
  {
    "id": "emp-043",
    "firstName": "Shreyas",
    "lastName": "Waghmare",
    "email": "shreyas.waghmare@company.com",
    "phone": "+91-9876557540",
    "department": "Human Resources",
    "designation": "HR Coordinator",
    "status": "active",
    "joiningDate": "2024-11-13",
    "dateOfBirth": "1991-08-28",
    "performanceRating": "Meets Expectations",
    "salary": 505812,
    "avatar": null,
    "documents": [],
    "address": "Deccan Gymkhana, Pune",
    "managerId": "emp-013"
  },
  {
    "id": "emp-044",
    "firstName": "Anagha",
    "lastName": "Sanap",
    "email": "anagha.sanap@company.com",
    "phone": "+91-9876579803",
    "department": "Design",
    "designation": "Graphic Designer",
    "status": "active",
    "joiningDate": "2025-07-22",
    "dateOfBirth": "2001-11-21",
    "performanceRating": "Exceeds Expectations",
    "salary": 740518,
    "avatar": null,
    "documents": [],
    "address": "Viman Nagar, Pune",
    "managerId": "emp-022"
  },
  {
    "id": "emp-045",
    "firstName": "Rohit",
    "lastName": "Pawar",
    "email": "rohit.pawar@company.com",
    "phone": "+91-9876585143",
    "department": "Engineering",
    "designation": "Developer",
    "status": "notice-period",
    "joiningDate": "2025-05-10",
    "dateOfBirth": "1999-03-28",
    "performanceRating": "Meets Expectations",
    "salary": 1295502,
    "avatar": null,
    "documents": [],
    "address": "Kalyani Nagar, Pune",
    "managerId": "emp-011"
  },
  {
    "id": "emp-046",
    "firstName": "Namrata",
    "lastName": "Kale",
    "email": "namrata.kale@company.com",
    "phone": "+91-9876532150",
    "department": "Operations",
    "designation": "Operations Analyst",
    "status": "inactive",
    "joiningDate": "2025-01-18",
    "dateOfBirth": "1997-03-24",
    "performanceRating": "Exceeds Expectations",
    "salary": 763050,
    "avatar": null,
    "documents": [],
    "address": "Aundh, Pune",
    "managerId": "emp-018"
  },
  {
    "id": "emp-047",
    "firstName": "Santosh",
    "lastName": "Vanjari",
    "email": "santosh.vanjari@company.com",
    "phone": "+91-9876522329",
    "department": "Finance",
    "designation": "Accountant",
    "status": "notice-period",
    "joiningDate": "2026-04-03",
    "dateOfBirth": "2000-12-22",
    "performanceRating": "Outstanding",
    "salary": 843785,
    "avatar": null,
    "documents": [],
    "address": "Baner, Pune",
    "managerId": "emp-015"
  },
  {
    "id": "emp-048",
    "firstName": "Swaranjali",
    "lastName": "Pawar",
    "email": "swaranjali.pawar@company.com",
    "phone": "+91-9876569710",
    "department": "Engineering",
    "designation": "Developer",
    "status": "inactive",
    "joiningDate": "2023-12-16",
    "dateOfBirth": "1996-06-21",
    "performanceRating": "Exceeds Expectations",
    "salary": 1181802,
    "avatar": null,
    "documents": [],
    "address": "Kharadi, Pune",
    "managerId": "emp-010"
  },
  {
    "id": "emp-049",
    "firstName": "Sanika",
    "lastName": "Khade",
    "email": "sanika.khade@company.com",
    "phone": "+91-9876551404",
    "department": "Design",
    "designation": "Graphic Designer",
    "status": "active",
    "joiningDate": "2024-12-27",
    "dateOfBirth": "1998-08-08",
    "performanceRating": "Exceeds Expectations",
    "salary": 1123375,
    "avatar": null,
    "documents": [],
    "address": "Kothrud, Pune",
    "managerId": "emp-022"
  },
  {
    "id": "emp-050",
    "firstName": "Sudhir",
    "lastName": "Darade",
    "email": "sudhir.darade@company.com",
    "phone": "+91-9876585328",
    "department": "Product",
    "designation": "Product Owner",
    "status": "inactive",
    "joiningDate": "2024-07-25",
    "dateOfBirth": "2000-06-25",
    "performanceRating": "Exceeds Expectations",
    "salary": 1081528,
    "avatar": null,
    "documents": [],
    "address": "Bhosari, Pune",
    "managerId": "emp-019"
  },
  {
    "id": "emp-051",
    "firstName": "Gauri",
    "lastName": "Vanjari",
    "email": "gauri.vanjari@company.com",
    "phone": "+91-9876544499",
    "department": "Operations",
    "designation": "Operations Analyst",
    "status": "on-leave",
    "joiningDate": "2023-12-09",
    "dateOfBirth": "1994-02-10",
    "performanceRating": "Outstanding",
    "salary": 1096156,
    "avatar": null,
    "documents": [],
    "address": "Deccan Gymkhana, Pune",
    "managerId": "emp-018"
  },
  {
    "id": "emp-052",
    "firstName": "Parth",
    "lastName": "Patil",
    "email": "parth.patil@company.com",
    "phone": "+91-9876554195",
    "department": "Engineering",
    "designation": "Senior Developer",
    "status": "inactive",
    "joiningDate": "2024-04-14",
    "dateOfBirth": "1996-01-13",
    "performanceRating": "Meets Expectations",
    "salary": 505252,
    "avatar": null,
    "documents": [],
    "address": "Magarpatta, Pune",
    "managerId": "emp-011"
  },
  {
    "id": "emp-053",
    "firstName": "Yash",
    "lastName": "Munde",
    "email": "yash.munde@company.com",
    "phone": "+91-9876552347",
    "department": "Operations",
    "designation": "Operations Analyst",
    "status": "active",
    "joiningDate": "2024-01-28",
    "dateOfBirth": "1996-05-18",
    "performanceRating": "Meets Expectations",
    "salary": 940479,
    "avatar": null,
    "documents": [],
    "address": "Kharadi, Pune",
    "managerId": "emp-018"
  },
  {
    "id": "emp-054",
    "firstName": "Ranjit",
    "lastName": "Raut",
    "email": "ranjit.raut@company.com",
    "phone": "+91-9876533210",
    "department": "Design",
    "designation": "Graphic Designer",
    "status": "active",
    "joiningDate": "2025-08-12",
    "dateOfBirth": "1993-01-28",
    "performanceRating": "Outstanding",
    "salary": 1154915,
    "avatar": null,
    "documents": [],
    "address": "Pimple Saudagar, Pune",
    "managerId": "emp-021"
  },
  {
    "id": "emp-055",
    "firstName": "Sushant",
    "lastName": "Waghmare",
    "email": "sushant.waghmare@company.com",
    "phone": "+91-9876557038",
    "department": "Operations",
    "designation": "Operations Analyst",
    "status": "notice-period",
    "joiningDate": "2026-04-22",
    "dateOfBirth": "2001-04-11",
    "performanceRating": "Exceeds Expectations",
    "salary": 1169724,
    "avatar": null,
    "documents": [],
    "address": "Magarpatta, Pune",
    "managerId": "emp-018"
  },
  {
    "id": "emp-056",
    "firstName": "Pranali",
    "lastName": "Gurav",
    "email": "pranali.gurav@company.com",
    "phone": "+91-9876547536",
    "department": "Design",
    "designation": "Graphic Designer",
    "status": "notice-period",
    "joiningDate": "2025-04-29",
    "dateOfBirth": "2001-08-11",
    "performanceRating": "Meets Expectations",
    "salary": 1007830,
    "avatar": null,
    "documents": [],
    "address": "Kalyani Nagar, Pune",
    "managerId": "emp-021"
  },
  {
    "id": "emp-057",
    "firstName": "Subhash",
    "lastName": "Gavali",
    "email": "subhash.gavali@company.com",
    "phone": "+91-9876593512",
    "department": "Product",
    "designation": "Product Owner",
    "status": "active",
    "joiningDate": "2026-05-08",
    "dateOfBirth": "2004-07-28",
    "performanceRating": "Exceeds Expectations",
    "salary": 1284841,
    "avatar": null,
    "documents": [],
    "address": "Camp, Pune",
    "managerId": "emp-020"
  },
  {
    "id": "emp-058",
    "firstName": "Kavita",
    "lastName": "Jadhav",
    "email": "kavita.jadhav@company.com",
    "phone": "+91-9876562810",
    "department": "Engineering",
    "designation": "Junior Developer",
    "status": "active",
    "joiningDate": "2025-11-19",
    "dateOfBirth": "1994-06-08",
    "performanceRating": "Meets Expectations",
    "salary": 702403,
    "avatar": null,
    "documents": [],
    "address": "Aundh, Pune",
    "managerId": "emp-011"
  },
  {
    "id": "emp-059",
    "firstName": "Sanket",
    "lastName": "Sable",
    "email": "sanket.sable@company.com",
    "phone": "+91-9876553808",
    "department": "Operations",
    "designation": "Operations Analyst",
    "status": "inactive",
    "joiningDate": "2025-07-24",
    "dateOfBirth": "1992-01-02",
    "performanceRating": "Meets Expectations",
    "salary": 502089,
    "avatar": null,
    "documents": [],
    "address": "Aundh, Pune",
    "managerId": "emp-018"
  },
  {
    "id": "emp-060",
    "firstName": "Shravani",
    "lastName": "Shelke",
    "email": "shravani.shelke@company.com",
    "phone": "+91-9876579557",
    "department": "Design",
    "designation": "Graphic Designer",
    "status": "active",
    "joiningDate": "2024-11-01",
    "dateOfBirth": "1996-06-30",
    "performanceRating": "Needs Improvement",
    "salary": 1249458,
    "avatar": null,
    "documents": [],
    "address": "Bavdhan, Pune",
    "managerId": "emp-021"
  },
  {
    "id": "emp-061",
    "firstName": "Nisha",
    "lastName": "Jadhav",
    "email": "nisha.jadhav@company.com",
    "phone": "+91-9876563523",
    "department": "Finance",
    "designation": "Accountant",
    "status": "on-leave",
    "joiningDate": "2024-10-18",
    "dateOfBirth": "1992-03-09",
    "performanceRating": "Needs Improvement",
    "salary": 784889,
    "avatar": null,
    "documents": [],
    "address": "Viman Nagar, Pune",
    "managerId": "emp-014"
  },
  {
    "id": "emp-062",
    "firstName": "Diksha",
    "lastName": "Dhumal",
    "email": "diksha.dhumal@company.com",
    "phone": "+91-9876573429",
    "department": "Design",
    "designation": "Graphic Designer",
    "status": "active",
    "joiningDate": "2025-01-16",
    "dateOfBirth": "2001-12-16",
    "performanceRating": "Exceeds Expectations",
    "salary": 861995,
    "avatar": null,
    "documents": [],
    "address": "Aundh, Pune",
    "managerId": "emp-021"
  },
  {
    "id": "emp-063",
    "firstName": "Nikita",
    "lastName": "Khandagale",
    "email": "nikita.khandagale@company.com",
    "phone": "+91-9876531396",
    "department": "Finance",
    "designation": "Accountant",
    "status": "inactive",
    "joiningDate": "2026-05-17",
    "dateOfBirth": "1998-04-07",
    "performanceRating": "Needs Improvement",
    "salary": 611563,
    "avatar": null,
    "documents": [],
    "address": "Wakad, Pune",
    "managerId": "emp-015"
  },
  {
    "id": "emp-064",
    "firstName": "Shrikant",
    "lastName": "Ghuge",
    "email": "shrikant.ghuge@company.com",
    "phone": "+91-9876591784",
    "department": "Product",
    "designation": "Product Owner",
    "status": "notice-period",
    "joiningDate": "2024-10-22",
    "dateOfBirth": "1997-05-24",
    "performanceRating": "Meets Expectations",
    "salary": 795153,
    "avatar": null,
    "documents": [],
    "address": "Hinjewadi, Pune",
    "managerId": "emp-019"
  },
  {
    "id": "emp-065",
    "firstName": "Sanjivani",
    "lastName": "Vanjari",
    "email": "sanjivani.vanjari@company.com",
    "phone": "+91-9876519931",
    "department": "Product",
    "designation": "Product Owner",
    "status": "active",
    "joiningDate": "2024-03-09",
    "dateOfBirth": "1998-11-07",
    "performanceRating": "Meets Expectations",
    "salary": 556628,
    "avatar": null,
    "documents": [],
    "address": "Wagholi, Pune",
    "managerId": "emp-019"
  }
];
