export const initialEmployees = [
  {
    id: "emp-001",
    firstName: "Amit",
    lastName: "Lakade",
    email: "amit.lakade@company.com",
    phone: "+91-9876543210",
    department: "Engineering",
    designation: "Senior Developer",
    status: "active",
    joiningDate: "2021-03-15",
    performanceRating: "Exceeds Expectations",
    salary: 1250000,
    avatar: null,
    documents: [],
    address: "Kothrud, Pune"
  },
  {
    id: "emp-002",
    firstName: "Priyanka",
    lastName: "Patil",
    email: "priyanka.patil@company.com",
    phone: "+91-9876543211",
    department: "Sales",
    designation: "Sales Manager",
    status: "active",
    joiningDate: "2022-06-01",
    performanceRating: "Meets Expectations",
    salary: 950000,
    avatar: null,
    documents: [],
    address: "Baner, Pune"
  },
  {
    id: "emp-003",
    firstName: "Rohan",
    lastName: "Deshmukh",
    email: "rohan.deshmukh@company.com",
    phone: "+91-9876543212",
    department: "Human Resources",
    designation: "HR Manager",
    status: "active",
    joiningDate: "2020-01-10",
    performanceRating: "Outstanding",
    salary: 1100000,
    avatar: null,
    documents: [],
    address: "Viman Nagar, Pune"
  },
  {
    id: "emp-004",
    firstName: "Sneha",
    lastName: "Kamble",
    email: "sneha.kamble@company.com",
    phone: "+91-9876543213",
    department: "Engineering",
    designation: "Tech Lead",
    status: "on-leave",
    joiningDate: "2019-11-20",
    performanceRating: "Exceeds Expectations",
    salary: 1800000,
    avatar: null,
    documents: [],
    address: "Hinjewadi, Pune"
  },
  {
    id: "emp-005",
    firstName: "Vikas",
    lastName: "Shinde",
    email: "vikas.shinde@company.com",
    phone: "+91-9876543214",
    department: "Finance",
    designation: "Financial Analyst",
    status: "notice-period",
    joiningDate: "2021-08-15",
    performanceRating: "Meets Expectations",
    salary: 800000,
    avatar: null,
    documents: [],
    address: "Magarpatta, Pune"
  },
  {
    id: "emp-006",
    firstName: "Anjali",
    lastName: "Pawar",
    email: "anjali.pawar@company.com",
    phone: "+91-9876543215",
    department: "Marketing",
    designation: "Marketing Specialist",
    status: "active",
    joiningDate: "2023-02-10",
    performanceRating: "Outstanding",
    salary: 750000,
    avatar: null,
    documents: [],
    address: "Kharadi, Pune"
  },
  {
    id: "emp-007",
    firstName: "Karan",
    lastName: "Chavan",
    email: "karan.chavan@company.com",
    phone: "+91-9876543216",
    department: "Operations",
    designation: "Operations Lead",
    status: "active",
    joiningDate: "2022-09-05",
    performanceRating: "Meets Expectations",
    salary: 1050000,
    avatar: null,
    documents: [],
    address: "Wakad, Pune"
  },
  {
    id: "emp-008",
    firstName: "Neha",
    lastName: "Gaikwad",
    email: "neha.gaikwad@company.com",
    phone: "+91-9876543217",
    department: "Product",
    designation: "Product Manager",
    status: "on-leave",
    joiningDate: "2020-07-22",
    performanceRating: "Exceeds Expectations",
    salary: 1600000,
    avatar: null,
    documents: [],
    address: "Aundh, Pune"
  },
  {
    id: "emp-009",
    firstName: "Siddharth",
    lastName: "Kale",
    email: "siddharth.kale@company.com",
    phone: "+91-9876543218",
    department: "Design",
    designation: "UI/UX Designer",
    status: "active",
    joiningDate: "2021-05-14",
    performanceRating: "Meets Expectations",
    salary: 900000,
    avatar: null,
    documents: [],
    address: "Shivaji Nagar, Pune"
  },
  {
    id: "emp-010",
    firstName: "Riya",
    lastName: "Bhalerao",
    email: "riya.bhalerao@company.com",
    phone: "+91-9876543219",
    department: "Engineering",
    designation: "Junior Developer",
    status: "inactive",
    joiningDate: "2022-01-10",
    performanceRating: "Needs Improvement",
    salary: 500000,
    avatar: null,
    documents: [],
    address: "Pimple Saudagar, Pune"
  },
  {
    id: "emp-011",
    firstName: "Sagar",
    lastName: "Jadhav",
    email: "sagar.jadhav@company.com",
    phone: "+91-9876543220",
    department: "Sales",
    designation: "Sales Executive",
    status: "active",
    joiningDate: "2023-11-01",
    performanceRating: "Meets Expectations",
    salary: 600000,
    avatar: null,
    documents: [],
    address: "Hadapsar, Pune"
  },
  {
    id: "emp-012",
    firstName: "Pooja",
    lastName: "More",
    email: "pooja.more@company.com",
    phone: "+91-9876543221",
    department: "Human Resources",
    designation: "HR Coordinator",
    status: "notice-period",
    joiningDate: "2021-09-01",
    performanceRating: "Meets Expectations",
    salary: 550000,
    avatar: null,
    documents: [],
    address: "Koregaon Park, Pune"
  },
  {
    id: "emp-013",
    firstName: "Vikram",
    lastName: "Waghmare",
    email: "vikram.waghmare@company.com",
    phone: "+91-9876543222",
    department: "Finance",
    designation: "Director",
    status: "active",
    joiningDate: "2018-04-15",
    performanceRating: "Outstanding",
    salary: 2800000,
    avatar: null,
    documents: [],
    address: "Kalyani Nagar, Pune"
  },
  {
    id: "emp-014",
    firstName: "Meera",
    lastName: "Thorat",
    email: "meera.thorat@company.com",
    phone: "+91-9876543223",
    department: "Marketing",
    designation: "Marketing Specialist",
    status: "active",
    joiningDate: "2024-01-15",
    performanceRating: "Exceeds Expectations",
    salary: 780000,
    avatar: null,
    documents: [],
    address: "Wagholi, Pune"
  },
  {
    id: "emp-015",
    firstName: "Rohan",
    lastName: "Mane",
    email: "rohan.mane@company.com",
    phone: "+91-9876543224",
    department: "Operations",
    designation: "Operations Lead",
    status: "on-leave",
    joiningDate: "2020-10-05",
    performanceRating: "Needs Improvement",
    salary: 950000,
    avatar: null,
    documents: [],
    address: "Bhosari, Pune"
  },
  {
    id: "emp-016",
    firstName: "Kavya",
    lastName: "Shirke",
    email: "kavya.shirke@company.com",
    phone: "+91-9876543225",
    department: "Product",
    designation: "Product Manager",
    status: "active",
    joiningDate: "2022-03-20",
    performanceRating: "Exceeds Expectations",
    salary: 1550000,
    avatar: null,
    documents: [],
    address: "Balewadi, Pune"
  },
  {
    id: "emp-017",
    firstName: "Aditya",
    lastName: "Kadam",
    email: "aditya.kadam@company.com",
    phone: "+91-9876543226",
    department: "Design",
    designation: "UI/UX Designer",
    status: "active",
    joiningDate: "2023-06-10",
    performanceRating: "Meets Expectations",
    salary: 850000,
    avatar: null,
    documents: [],
    address: "Deccan Gymkhana, Pune"
  },
  {
    id: "emp-018",
    firstName: "Divya",
    lastName: "Bhosale",
    email: "divya.bhosale@company.com",
    phone: "+91-9876543227",
    department: "Engineering",
    designation: "Engineering Manager",
    status: "active",
    joiningDate: "2019-02-18",
    performanceRating: "Outstanding",
    salary: 2400000,
    avatar: null,
    documents: [],
    address: "Pashan, Pune"
  },
  {
    id: "emp-019",
    firstName: "Suresh",
    lastName: "Salunkhe",
    email: "suresh.salunkhe@company.com",
    phone: "+91-9876543228",
    department: "Sales",
    designation: "Vice President",
    status: "inactive",
    joiningDate: "2017-08-01",
    performanceRating: "Meets Expectations",
    salary: 3500000,
    avatar: null,
    documents: [],
    address: "Camp, Pune"
  },
  {
    id: "emp-020",
    firstName: "Ishaan",
    lastName: "Desai",
    email: "ishaan.desai@company.com",
    phone: "+91-9876543229",
    department: "Engineering",
    designation: "Junior Developer",
    status: "active",
    joiningDate: new Date().toISOString().split('T')[0], // Current month joiner
    performanceRating: "Meets Expectations",
    salary: 450000,
    avatar: null,
    documents: [],
    address: "Warje, Pune"
  },
  {
    id: "emp-021",
    firstName: "Nidhi",
    lastName: "Sawant",
    email: "nidhi.sawant@company.com",
    phone: "+91-9876543230",
    department: "Finance",
    designation: "Financial Analyst",
    status: "active",
    joiningDate: "2022-12-05",
    performanceRating: "Exceeds Expectations",
    salary: 820000,
    avatar: null,
    documents: [],
    address: "Sinhagad Road, Pune"
  },
  {
    id: "emp-022",
    firstName: "Rajesh",
    lastName: "Raut",
    email: "rajesh.raut@company.com",
    phone: "+91-9876543231",
    department: "Marketing",
    designation: "Marketing Specialist",
    status: "notice-period",
    joiningDate: "2021-07-20",
    performanceRating: "Needs Improvement",
    salary: 700000,
    avatar: null,
    documents: [],
    address: "Kothrud, Pune"
  },
  {
    id: "emp-023",
    firstName: "Swati",
    lastName: "Munde",
    email: "swati.munde@company.com",
    phone: "+91-9876543232",
    department: "Operations",
    designation: "Operations Lead",
    status: "active",
    joiningDate: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString().split('T')[0], // Current month joiner
    performanceRating: "Meets Expectations",
    salary: 1100000,
    avatar: null,
    documents: [],
    address: "Wakad, Pune"
  },
  {
    id: "emp-024",
    firstName: "Manoj",
    lastName: "Dhasal",
    email: "manoj.dhasal@company.com",
    phone: "+91-9876543233",
    department: "Product",
    designation: "Product Manager",
    status: "active",
    joiningDate: "2021-09-15",
    performanceRating: "Exceeds Expectations",
    salary: 1650000,
    avatar: null,
    documents: [],
    address: "Baner, Pune"
  },
  {
    id: "emp-025",
    firstName: "Tara",
    lastName: "Gavali",
    email: "tara.gavali@company.com",
    phone: "+91-9876543234",
    department: "Design",
    designation: "UI/UX Designer",
    status: "on-leave",
    joiningDate: "2023-04-10",
    performanceRating: "Outstanding",
    salary: 950000,
    avatar: null,
    documents: [],
    address: "Bavdhan, Pune"
  }
];

export const attendanceData = [
  { month: 'Aug 2025', present: 92, absent: 8 },
  { month: 'Sep 2025', present: 88, absent: 12 },
  { month: 'Oct 2025', present: 95, absent: 5 },
  { month: 'Nov 2025', present: 90, absent: 10 },
  { month: 'Dec 2025', present: 85, absent: 15 },
  { month: 'Jan 2026', present: 93, absent: 7 },
  { month: 'Feb 2026', present: 96, absent: 4 },
  { month: 'Mar 2026', present: 94, absent: 6 },
  { month: 'Apr 2026', present: 91, absent: 9 },
  { month: 'May 2026', present: 89, absent: 11 },
  { month: 'Jun 2026', present: 95, absent: 5 },
  { month: 'Jul 2026', present: 97, absent: 3 },
];
